### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by wsslfnstr** [Slluxx/Fivereborn-Webmanager#1]
I cant get a connection but no error.
or is it connected if i var_dump the $con:

object(q3query)#2 (5) { ["address":"q3query":private]=> string(9) "127.0.0.1" ["port":"q3query":private]=> string(5) "30120" ["rconpassword":"q3query":private]=> string(9) "*-*-*" ["fp":"q3query":private]=> resource(5) of type (stream) ["lastPing":"q3query":private]=> bool(false) }

**Comment by Slluxx** [comment]
You only have to fill in your serverdetails into index.php. You dont have to dump anything or modify the code in any way. If you filled everything in but no players sho up, make sure your firewalls ( pc / server /.. ) allow connections.
