### ISSUE TITLE
Object not found. ERROR

### ISSUE THREAD

**Issue by rubeste** [Slluxx/Fivereborn-Webmanager#3]
I am having an issue.
When i press the kick button i get a message showing "Object not found!"
I am Using XAMPP for testing the FiveM Webmanager.
If some one can help it would be nice.
Thank you for reading.

**Comment by Slluxx** [comment]
Did you properly include the q3query.class.php ?

**Comment by rubeste** [comment]
Thank you. I changed the location of the file from "./rcon/q3query.class.php" to "rcon/q3query.class.php" and it worked.
